# permissions for end users to view canaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canary-viewer-role
rules:
- apiGroups:
  - canary.strimzi.io
  resources:
  - canaries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - canary.strimzi.io
  resources:
  - canaries/status
  verbs:
  - get
